### ISSUE TITLE
tests failing on `armhf` & `armel`

### ISSUE THREAD

**Issue by tenzap** [SergioBenitez/state#30]
The test suite is failing on archs `armel` and `armhf`.

This is revealed by the Debian package. Please note that the debian package patches loom out this way:
https://sources.debian.org/src/rust-state/0.6.0-1/debian/patches/loom-drop-cfg.patch/

#### Error on armhf
```
running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'test', '--verbose', '--verbose', '-j16', '--target', 'armv7-unknown-linux-gnueabihf', '--all-targets', '--all-features'],) {}
```
```
 83s running 24 tests
 83s test cell_tests::no_double_put ... ok
 83s test type_map_tests::drop_inners_on_drop ... ok
 83s test cell_tests::simple_put_get ... ok
 83s test cell_tests::drop_inners_on_drop ... ok
 83s test type_map_tests::set_get_remote ... ok
 83s test cell_tests::clone ... ok
 83s test type_map_tests::simple_set_get ... ok
 83s test type_map_tests::test_no_drop_on_set ... ok
 83s test type_map_tests_tls::test_double_put ... ok
 83s test cell_tests_tls::no_double_put ... ok
 83s test type_map_tests_tls::test_simple ... ok
 83s test type_map_tests_tls::type_map_tls_really_is_tls_take_2 ... ok
 83s test type_map_tests::dst_set_get ... ok
 83s test cell_tests_tls::simple_put_get ... ok
 83s test type_map_tests::two_put_get ... ok
 83s test test_dropping_struct ... ok
 83s test type_map_tests_tls::not_unique_when_sent ... ok
 83s test cell_tests::dst_set_get ... ok
 84s test cell_tests_tls::cell_tls_really_is_tls_take_2 ... ok
 84s test type_map_tests_tls::type_map_tls_really_is_tls ... ok
 84s test cell_tests_tls::cell_tls_really_is_tls ... ok
 86s test cell_tests_tls::many_puts_only_one_succeeds ... FAILED
 86s test cell_tests::many_puts_only_one_succeeds ... FAILED
 86s test type_map_tests::many_puts_only_one_succeeds ... FAILED
 86s 
 86s failures:
 86s 
 86s ---- cell_tests_tls::many_puts_only_one_succeeds stdout ----
 86s thread 'cell_tests_tls::many_puts_only_one_succeeds' panicked at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:29:
 86s failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
 86s stack backtrace:
 86s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 86s 
 86s ---- cell_tests::many_puts_only_one_succeeds stdout ----
 86s thread 'cell_tests::many_puts_only_one_succeeds' panicked at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:29:
 86s failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
 86s stack backtrace:
 86s    0: rust_begin_unwind
 86s              at /usr/src/rustc-1.82.0/library/std/src/panicking.rs:662:5
 86s    1: core::panicking::panic_fmt
 86s              at /usr/src/rustc-1.82.0/library/core/src/panicking.rs:74:14
 86s    2: core::result::unwrap_failed
 86s              at /usr/src/rustc-1.82.0/library/core/src/result.rs:1677:5
 86s    3: core::result::Result<T,E>::expect
 86s              at /usr/src/rustc-1.82.0/library/core/src/result.rs:1059:23
 86s    4: std::thread::spawn
 86s              at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:5
 86s    5: main::cell_tests::many_puts_only_one_succeeds
 86s              at ./tests/main.rs:235:26
 86s    6: main::cell_tests::many_puts_only_one_succeeds::{{closure}}
 86s              at ./tests/main.rs:230:37
 86s    7: core::ops::function::FnOnce::call_once
 86s              at /usr/src/rustc-1.82.0/library/core/src/ops/function.rs:250:5
 86s    8: core::ops::function::FnOnce::call_once
 86s              at /usr/src/rustc-1.82.0/library/core/src/ops/function.rs:250:5
 86s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 86s 
 86s ---- type_map_tests::many_puts_only_one_succeeds stdout ----
 86s thread 'type_map_tests::many_puts_only_one_succeeds' panicked at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:29:
 86s failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
 86s stack backtrace:
 86s    0: rust_begin_unwind
 86s              at /usr/src/rustc-1.82.0/library/std/src/panicking.rs:662:5
 86s    1: core::panicking::panic_fmt
 86s              at /usr/src/rustc-1.82.0/library/core/src/panicking.rs:74:14
 86s    2: core::result::unwrap_failed
 86s              at /usr/src/rustc-1.82.0/library/core/src/result.rs:1677:5
 86s    3: core::result::Result<T,E>::expect
 86s              at /usr/src/rustc-1.82.0/library/core/src/result.rs:1059:23
 86s    4: std::thread::spawn
 86s              at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:5
 86s    5: main::type_map_tests::many_puts_only_one_succeeds
 86s              at ./tests/main.rs:78:26
 86s    6: main::type_map_tests::many_puts_only_one_succeeds::{{closure}}
 86s              at ./tests/main.rs:75:37
 86s    7: core::ops::function::FnOnce::call_once
 86s              at /usr/src/rustc-1.82.0/library/core/src/ops/function.rs:250:5
 86s    8: core::ops::function::FnOnce::call_once
 86s              at /usr/src/rustc-1.82.0/library/core/src/ops/function.rs:250:5
 86s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 86s 
 86s 
 86s failures:
 86s     cell_tests::many_puts_only_one_succeeds
 86s     cell_tests_tls::many_puts_only_one_succeeds
 86s     type_map_tests::many_puts_only_one_succeeds
 86s 
 86s test result: FAILED. 21 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.03s
 86s 
 86s error: test failed, to rerun pass `--test main`
 87s autopkgtest [18:22:48]: test rust-state:@: -----------------------]

```

#### Error on armel
```
running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'test', '--verbose', '--verbose', '-j16', '--target', 'armv5te-unknown-linux-gnueabi', '--all-targets', '--all-features'],) {}
```

```
110s running 24 tests
110s test cell_tests::drop_inners_on_drop ... ok
110s test cell_tests::clone ... ok
110s test cell_tests::simple_put_get ... ok
110s test cell_tests::dst_set_get ... ok
110s test cell_tests::no_double_put ... ok
110s test cell_tests_tls::simple_put_get ... ok
110s test cell_tests_tls::no_double_put ... ok
110s test test_dropping_struct ... ok
110s test type_map_tests::drop_inners_on_drop ... ok
110s test type_map_tests::simple_set_get ... ok
110s test type_map_tests::dst_set_get ... ok
110s test type_map_tests::two_put_get ... ok
110s test cell_tests_tls::cell_tls_really_is_tls_take_2 ... ok
110s test type_map_tests_tls::test_double_put ... ok
110s test type_map_tests::test_no_drop_on_set ... ok
110s test type_map_tests_tls::test_simple ... ok
110s test type_map_tests::set_get_remote ... ok
110s test type_map_tests_tls::type_map_tls_really_is_tls_take_2 ... ok
110s test type_map_tests_tls::not_unique_when_sent ... ok
110s test cell_tests_tls::cell_tls_really_is_tls ... ok
110s test type_map_tests_tls::type_map_tls_really_is_tls ... ok
110s test cell_tests::many_puts_only_one_succeeds ... FAILED
110s test type_map_tests::many_puts_only_one_succeeds ... FAILED
111s test cell_tests_tls::many_puts_only_one_succeeds ... FAILED
111s 
111s failures:
111s 
111s ---- cell_tests::many_puts_only_one_succeeds stdout ----
111s thread 'cell_tests::many_puts_only_one_succeeds' panicked at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:29:
111s failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
111s stack backtrace:
111s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
111s 
111s ---- type_map_tests::many_puts_only_one_succeeds stdout ----
111s thread 'type_map_tests::many_puts_only_one_succeeds' panicked at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:29:
111s failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
111s stack backtrace:
111s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
111s 
111s ---- cell_tests_tls::many_puts_only_one_succeeds stdout ----
111s thread 'cell_tests_tls::many_puts_only_one_succeeds' panicked at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:29:
111s failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
111s stack backtrace:
111s    0: rust_begin_unwind
111s              at /usr/src/rustc-1.82.0/library/std/src/panicking.rs:662:5
111s    1: core::panicking::panic_fmt
111s              at /usr/src/rustc-1.82.0/library/core/src/panicking.rs:74:14
111s    2: core::result::unwrap_failed
111s              at /usr/src/rustc-1.82.0/library/core/src/result.rs:1677:5
111s    3: core::result::Result<T,E>::expect
111s              at /usr/src/rustc-1.82.0/library/core/src/result.rs:1059:23
111s    4: std::thread::spawn
111s              at /usr/src/rustc-1.82.0/library/std/src/thread/mod.rs:678:5
111s    5: main::cell_tests_tls::many_puts_only_one_succeeds
111s              at ./tests/main.rs:315:26
111s    6: main::cell_tests_tls::many_puts_only_one_succeeds::{{closure}}
111s              at ./tests/main.rs:310:37
111s    7: core::ops::function::FnOnce::call_once
111s              at /usr/src/rustc-1.82.0/library/core/src/ops/function.rs:250:5
111s    8: core::ops::function::FnOnce::call_once
111s              at /usr/src/rustc-1.82.0/library/core/src/ops/function.rs:250:5
111s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
111s 
111s 
111s failures:
111s     cell_tests::many_puts_only_one_succeeds
111s     cell_tests_tls::many_puts_only_one_succeeds
111s     type_map_tests::many_puts_only_one_succeeds
111s 
111s test result: FAILED. 21 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.80s
111s 
111s error: test failed, to rerun pass `--test main`
112s autopkgtest [18:21:53]: test rust-state:@: -----------------------]

```

**Comment by tenzap** [comment]
@SergioBenitez, gentle ping.
